doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        mapping_types:
            # doctrine + postgres sometimes screws up and prefixes text with an _...
            _text: string
        types:
            datetime: Shared\Infrastructure\Doctrine\Types\DatetimeDbalType
            uuid: Shared\Infrastructure\Doctrine\Types\UuidDbalType
            email: Shared\Infrastructure\Doctrine\Types\EmailDbalType

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App\Modules\Users\Domain\User:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/src/Modules/Users/Infrastructure/DoctrineMappings'
                prefix: 'App\Modules\Users\Domain'
                alias: User
            App\Modules\Posts\Domain\Post:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/src/Modules/Posts/Infrastructure/DoctrineMappings'
                prefix: 'App\Modules\Posts\Domain'
                alias: Post
